const ShowData = [
  {
    id: "4eb0e331-7239-40cd-b87e-ca536e2d48a8",
    sku: "DO9825-902",
    brand: "Nike",
    name: "Boi-1da x KD 15 'Producer Pack - 86 BPM'",
    colorway: "Multi-Color/Multi-Color",
    gender: "men",
    silhouette: "KD 15",
    releaseYear: "2022",
    releaseDate: "2022-09-22",
    retailPrice: 160,
    estimatedMarketValue: 239,
    image:
      "https://image.goat.com/attachments/product_template_pictures/images/076/953/189/original/CT8013_071.png.png",
    story:
      "Designed in collaboration with the Canadian hip-hop producer, the Boi-1da x Nike KD 15 ‘Producer Pack - 86 BPM’ reflects Kevin Durant’s passion for music. The upper is composed of black perforated leather and patterned knit textile in black and grey. Integrated into the laces, charcoal TPU wings are contrasted by a signature Swoosh in a gradient blend of neon green and fuchsia. ’86 BPM’ is embroidered across the back heel, while mismatched tongue branding features KD’s logo on the left tongue and Boi-1da’s signature on the right. Performance benefits include an Air Zoom Strobel, Cushlon midsole, and a grippy rubber outsole inspired by a topographical map.",
  },
  {
    id: "4eac5723-654e-4d54-abcd-5b1a01ca6fd4",
    sku: "DZ2523-001",
    brand: "Jordan",
    name: "Wmns Air Jordan 1 Retro High OG 'Twist 2.0'",
    colorway: "Medium Grey/Black/White",
    gender: "women",
    silhouette: "Air Jordan 1",
    releaseYear: "2022",
    releaseDate: "2022-12-22",
    retailPrice: 0,
    estimatedMarketValue: 450,
    image: "",
    story:
      "The women’s Air Jordan 1 Retro High OG ‘Twist 2.0’ presents the sequel to the AJ1 ‘Twist’ from 2019, featuring the same unique build but with a subtly refreshed palette. Like the older shoe, the upper pairs black pony hair with a smooth leather underlay. The latter is updated in a light grey hue, replacing the crisp white finish of the original. A molded Wings logo in metallic silver shines on the lateral collar, adding a bit of polish to the neutral design.",
  },
  {
    id: "4cfbea95-1c4c-46c5-a5d3-4bd140b67b34",
    sku: "M990TO3",
    brand: "New Balance",
    name: "Teddy Santis x 990v3 Made in USA 'Olive'",
    colorway: "",
    gender: "men",
    silhouette: "990v3",
    releaseYear: "2022",
    releaseDate: "2022-09-22",
    retailPrice: 200,
    estimatedMarketValue: 398,
    story: "",
    image:
      "https://image.goat.com/attachments/product_template_pictures/images/076/953/189/original/CT8013_071.png.png",
  },
  {
    id: "93c2660a-9f81-4771-a3ef-04cd5c68f012",
    sku: "HQ3969",
    brand: "adidas",
    name: "NMD_V3 'Solar Yellow'",
    colorway: "Solar Yellow/Solar Yellow/Core Black",
    gender: "men",
    silhouette: "NMD_V3",
    releaseYear: "2022",
    releaseDate: "2022-09-22",
    image: "",
    retailPrice: 160,
    estimatedMarketValue: 350,
    story:
      "The adidas NMD_V3 ‘Solar Yellow’ showcases an eye-catching hue on a knit textile upper made with a 50/50 blend of Parley Ocean Plastic and recycled polyester. Perforations on the toe box and quarter panel deliver enhanced breathability, while reflective accents provide added visibility in low-light conditions. The lightweight build sits atop a full-length Boost midsole, partially enveloped in a translucent TPU cage for improved durability and a stable ride.",
  },
];
